# Generated by Django 4.2.14 on 2024-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_position',
            field=models.CharField(choices=[('', 'select'), ('Manager', 'Manager'), ('cashier', 'cashier'), ('DBM', 'DBM'), ('sales executive', 'sales executive'), ('BRM', 'BRM')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_salary',
            field=models.IntegerField(),
        ),
    ]
